cdc/urls.py
from django.contrib import admin
from django.urls import path,include
import main.urls
import user.urls
import finance.urls
import corecode.urls
import libman.urls

from . import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('finance/',include("finance.urls")),
    path('user/',include("user.urls")),
    path('others/',include("corecode.urls")),
    path('asset',include("asset.urls")),
    path('library',include("libman.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

corecode/urls.py
from django.urls import path

from . import views

app_name='corecode'

urlpatterns = [
  path('', views.index_view, name='home'),
  path('site-config', views.siteconfig_view, name='configs'),
  path('current-session/', views.current_session_view, name='current-session'),

  path('year/list/', views.SessionListView.as_view(), name='sessions'),
  path('year/create/', views.SessionCreateView.as_view(), name='session-create'),
  path('year/<int:pk>/update/',
       views.SessionUpdateView.as_view(), name='session-update'),
  path('year/<int:pk>/delete/',
       views.SessionDeleteView.as_view(), name='session-delete'),

  path('month/list/', views.TermListView.as_view(), name='terms'),
  path('month/create/', views.TermCreateView.as_view(), name='term-create'),
  path('month/<int:pk>/update/',
       views.TermUpdateView.as_view(), name='term-update'),
  path('month/<int:pk>/delete/',
       views.TermDeleteView.as_view(), name='term-delete'),

  path('class/list/', views.ClassListView.as_view(), name='classes'),
  path('class/create/', views.ClassCreateView.as_view(), name='class-create'),
  path('class/<int:pk>/update/',
       views.ClassUpdateView.as_view(), name='class-update'),
  path('class/<int:pk>/delete/',
       views.ClassDeleteView.as_view(), name='class-delete'),

  path('subject/list/', views.SubjectListView.as_view(), name='subjects'),
  path('subject/create/', views.SubjectCreateView.as_view(),
       name='subject-create'),
  path('subject/<int:pk>/update/',
       views.SubjectUpdateView.as_view(), name='subject-update'),
  path('subject/<int:pk>/delete/',
       views.SubjectDeleteView.as_view(), name='subject-delete'),

  path('category/list',views.ExpenseCategoryListView.as_view(),name='category'),
  path('category/create',views.ExpenseCategoryCreateView.as_view(),name='category-create'),
  path('category/<int:pk>/update',views.ExpenseCategoryUpdateView.as_view(),name='category-update'),
  path('category/<int:pk>/delete',views.ExpenseCategoryDeleteView.as_view(),name='category-delete'),

]

corecode/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.


class SiteConfig(models.Model):
  """ Site Configurations """
  key = models.SlugField()
  value = models.CharField(max_length=200)

  def __str__(self):
    return self.key


class AcademicSession(models.Model):
  """ Academic Session """
  name = models.CharField(max_length=200, unique=True)
  current = models.BooleanField(default=False, null=True)

  class Meta:
    ordering = ['id']

  def __str__(self):
    return self.name


class AcademicTerm(models.Model):
  """ Academic Term """
  name = models.CharField(max_length=20, unique=True)
  current = models.BooleanField(default=False, null=True)

  class Meta:
    ordering = ['id']

  def __str__(self):
    return self.name


class Subject(models.Model):
  """ Subject """
  name = models.CharField(max_length=200, unique=True)

  class Meta:
    ordering = ['name']

  def __str__(self):
    return self.name


class StudentClass(models.Model):
  name = models.CharField(max_length=200, unique=True)

  class Meta:
    verbose_name = "Class"
    verbose_name_plural = "Classes"
    ordering = ['name']

  def __str__(self):
    return self.name

class ExpenseCategory(models.Model):
  name=models.CharField(max_length=200,unique=True)

  def __str__(self):
    return self.name

corecode/forms.py
from django import forms
from django.forms import ModelForm, modelformset_factory

from .models import SiteConfig, AcademicTerm, AcademicSession, StudentClass, Subject,ExpenseCategory

SiteConfigForm = modelformset_factory(SiteConfig, fields=('key', 'value',), extra=0)

class AcademicSessionForm(ModelForm):
  prefix = 'Academic Session'
  class Meta:
    model = AcademicSession
    fields = ['name','current']

class AcademicTermForm(ModelForm):
  prefix = 'Academic Term'
  class Meta:
    model = AcademicTerm
    fields = ['name','current']

class SubjectForm(ModelForm):
  prefix = 'Subject'
  class Meta:
    model = Subject
    fields = ['name']

class StudentClassForm(ModelForm):
  prefix = 'Class'
  class Meta:
    model = StudentClass
    fields = ['name']

class CurrentSessionForm(forms.Form):
  current_year = forms.ModelChoiceField(queryset=AcademicSession.objects.all(), help_text='Click <a href="/session/create/?next=current-session/">here</a> to add new session')
  current_month = forms.ModelChoiceField(queryset=AcademicTerm.objects.all(), help_text='Click <a href="/term/create/?next=current-session/">here</a> to add new term')

class ExpenseCategoryForm(forms.ModelForm):
  prefix='Expense'
  class Meta:
    model=ExpenseCategory
    fields=['name']

corecode/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import SiteConfig, AcademicSession, AcademicTerm, StudentClass, Subject,ExpenseCategory
from .forms import SiteConfigForm,ExpenseCategoryForm, AcademicTermForm, AcademicSessionForm, StudentClassForm, SubjectForm, CurrentSessionForm

# Create your views here.
@login_required
def index_view(request):
  return render(request, 'index.html')

@login_required
def siteconfig_view(request):
  """ Site Config View """
  if request.method == 'POST':
    form = SiteConfigForm(request.POST)
    if form.is_valid():
      form.save()
      messages.success(request, 'Configurations successfully updated')
      return HttpResponseRedirect('site-config')
  else:
    form = SiteConfigForm(queryset=SiteConfig.objects.all())

  context = {"formset": form, "title": "Configuration"}
  return render(request, 'corecode/siteconfig.html', context)


class SessionListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
  model = AcademicSession
  template_name = 'corecode/session_list.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['form'] = AcademicSessionForm()
      return context



class SessionCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
  form_class = AcademicSessionForm
  template_name = 'corecode/mgt_form.html'
  success_url = reverse_lazy('corecode:sessions')
  success_message = 'New session successfully added'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['title'] = 'Add new session'
      return context



class SessionUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
  model = AcademicSession
  fields = ['name', 'current']
  success_url = reverse_lazy('corecode:sessions')
  success_message = 'Session successfully updated.'
  template_name = 'corecode/mgt_form.html'


  def form_valid(self, form):
    obj = self.object
    if obj.current == False:
      terms = AcademicSession.objects.filter(
          current=True).exclude(name=obj.name).exists()
      if not terms:
        messages.warning(self.request, 'You must set a session to current.')
        return redirect('session-list')
    return super().form_valid(form)


class SessionDeleteView(LoginRequiredMixin, DeleteView):
  model = AcademicSession
  success_url = reverse_lazy('corecode:sessions')
  template_name = 'corecode/core_confirm_delete.html'
  success_message = "The session {} has been deleted with all its attached content"


  def delete(self, request, *args, **kwargs):
      obj = self.get_object()
      if obj.current == True:
        messages.warning(request, 'Cannot delete session as it is set to current')
        return redirect('corecode:sessions')
      messages.success(self.request, self.success_message.format(obj.name))
      return super(SessionDeleteView, self).delete(request, *args, **kwargs)

#academic terms

class TermListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
  model = AcademicTerm
  template_name = 'corecode/term_list.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['form'] = AcademicTermForm()
      return context



class TermCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
  form_class = AcademicTermForm
  template_name = 'corecode/mgt_form.html'
  success_url = reverse_lazy('corecode:terms')
  success_message = 'New term successfully added'



class TermUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
  form_class = AcademicTermForm
  success_url = reverse_lazy('corecode:terms')
  success_message = 'Term successfully updated.'
  template_name = 'corecode/mgt_form.html'
  model=AcademicTerm


  def form_valid(self, form):
    obj = self.object
    if obj.current == False:
      terms = AcademicTerm.objects.filter(current=True).exclude(name=obj.name).exists()
      if not terms:
        messages.warning(self.request, 'You must set a term to current.')
        return redirect('term')
    return super().form_valid(form)


class TermDeleteView(LoginRequiredMixin, DeleteView):
  model = AcademicTerm
  success_url = reverse_lazy('corecode:terms')
  template_name = 'corecode/core_confirm_delete.html'
  success_message = "The term {} has been deleted with all its attached content"


  def delete(self, request, *args, **kwargs):
      obj = self.get_object()
      if obj.current == True:
        messages.warning(request, 'Cannot delete term as it is set to current')
        return redirect('terms')
      messages.success(self.request, self.success_message.format(obj.name))
      return super(TermDeleteView, self).delete(request, *args, **kwargs)
#class


class ClassListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
  model = StudentClass
  template_name = 'corecode/class_list.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['form'] = StudentClassForm()
      return context



class ClassCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
  form_class = StudentClassForm
  template_name = 'corecode/mgt_form.html'
  success_url = reverse_lazy('classes')
  success_message = 'New class successfully added'



class ClassUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
  model = StudentClass
  fields = ['name']
  success_url = reverse_lazy('classes')
  success_message = 'class successfully updated.'
  template_name = 'corecode/mgt_form.html'



class ClassDeleteView(LoginRequiredMixin, DeleteView):
  model = StudentClass
  success_url = reverse_lazy('classes')
  template_name = 'corecode/core_confirm_delete.html'
  success_message = "The class {} has been deleted with all its attached content"


  def delete(self, request, *args, **kwargs):
      obj = self.get_object()
      print(obj.name)
      messages.success(self.request, self.success_message.format(obj.name))
      return super(ClassDeleteView, self).delete(request, *args, **kwargs)

#subject


class SubjectListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
  model = Subject
  template_name = 'corecode/subject_list.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['form'] = SubjectForm()
      return context



class SubjectCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
  form_class = SubjectForm
  template_name = 'corecode/mgt_form.html'
  success_url = reverse_lazy('subjects')
  success_message = 'New subject successfully added'



class SubjectUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
  model = Subject
  fields = ['name']
  success_url = reverse_lazy('subjects')
  success_message = 'Subject successfully updated.'
  template_name = 'corecode/mgt_form.html'



class SubjectDeleteView(LoginRequiredMixin, DeleteView):
  model = Subject
  success_url = reverse_lazy('subjects')
  template_name = 'corecode/core_confirm_delete.html'
  success_message = "The subject {} has been deleted with all its attached content"

  def delete(self, request, *args, **kwargs):
      obj = self.get_object()
      messages.success(self.request, self.success_message.format(obj.name))
      return super(SubjectDeleteView, self).delete(request, *args, **kwargs)


@login_required
def current_session_view(request):
  """ Current SEssion and Term """
  if request.method == 'POST':
    form = CurrentSessionForm(request.POST)
    if form.is_valid():
      session = form.cleaned_data['current_session']
      term = form.cleaned_data['current_term']
      AcademicSession.objects.filter(name=session).update(current=True)
      AcademicSession.objects.exclude(name=session).update(current=False)
      AcademicTerm.objects.filter(name=term).update(current=True)
      AcademicTerm.objects.exclude(name=term).update(current=False)

  else:
    form = CurrentSessionForm(initial={
      "current_session": AcademicSession.objects.get(current=True),
      "current_term": AcademicTerm.objects.get(current=True)
    })


  return render(request, 'corecode/current_session.html', {"form":form})

class ExpenseCategoryListView(SuccessMessageMixin, ListView):
  model = ExpenseCategory
  template_name = 'corecode/expense_category_list.html'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['form'] = ExpenseCategoryForm()
      return context



class ExpenseCategoryCreateView(SuccessMessageMixin, CreateView):
  form_class = ExpenseCategoryForm
  template_name = 'corecode/mgt_form.html'
  success_url = reverse_lazy('category')
  success_message = 'New Category successfully added'

class ExpenseCategoryUpdateView(SuccessMessageMixin, UpdateView):
  model = ExpenseCategory
  fields = ['name']
  success_url = reverse_lazy('category')
  success_message = 'Subject successfully updated.'
  template_name = 'corecode/mgt_form.html'

class ExpenseCategoryDeleteView(DeleteView):
  model = ExpenseCategory
  success_url = reverse_lazy('category')
  template_name = 'corecode/core_confirm_delete.html'
  success_message = "The class {} has been deleted with all its attached content"


  def delete(self, request, *args, **kwargs):
      obj = self.get_object()
      print(obj.name)
      messages.success(self.request, self.success_message.format(obj.name))
      return super(ExpenseCategoryDeleteView, self).delete(request, *args, **kwargs)

corecode/templates/corecode/class_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Classes
{% endblock title %}


{% block breadcrumb %}
  <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal1">
    <i class="fa fa-plus"></i>
    Add new class
  </a>
{% endblock breadcrumb %}
  

{% block content %}
  <div class="row">
    <div class="col-sm-12">

        <table class="table table-bordered">
          <tbody>
            {% for object in object_list %}
            <tr>
              <td>{{ object }}</td>
              <td><a href="{% url 'corecode:class-update' object.id %}"><i
                    class="fa fa-edit"></i></a>
                  <a  href="{% url 'corecode:class-delete' object.id %}"><i
                    class="fa fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

    </div>
  </div>


  <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'class-create' %}" method="POST">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add new class</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              {% csrf_token %}

              {% for field in form %}
                  <div class="form-group">
                    {{field.label_tag}}
                    {{ field|add_class:"form-control" }}
                    {{field.help_text}}
                    {{field.errors}}
                  </div>
              {% endfor %}
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

corecode/templates/corecode/core_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
delete page
{% endblock title %}


{% block content %}
  <div class="row">
    <div class="col-sm-12">
      <div class="card">
        <div class="card-body">
          <p>Are you sure you want to delete object <strong>{{ object}}</strong>
            alongside all attached contents?</p>
          <div class="mt-2 red-text">This action cannot be undone</div>

          <form method="POST" class="mt-3">
            {% csrf_token %}

            <button type="submit" class="btn btn-primary">
              Confirm Delete
              <i class="fa fa-trash-alt"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

corecode/templates/corecode/current_session.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
Set Current Year and Month
{% endblock title %}


{% block main %}
<div class="container-right">
  <br>
<form method="POST">
  {% csrf_token %}

  <div class="mb-3">
    {% for field in form %}
    <div class="form-group row">
      <div class="col-2">{{ field.label_tag}}</div>
      <div class="col-6">
        {{ field | add_class:"form-control"}}
        <!--<span class="small">{{ field.help_text |safe}}</span>-->
      </div>
    </div>
    {% endfor %}
  </div>


  <input type="submit" value="Save" class="w-25 btn btn-primary">

</form>
</div>
{% endblock main %}

corecode/templates/corecode/expense_category_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Expense Category
{% endblock title %}


{% block breadcrumb %}
  <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal1">
    <i class="fa fa-plus"></i>
    Add new Category
  </a>
{% endblock breadcrumb %}
  

{% block content %}
  <div class="row">
    <div class="col-sm-12">

        <table class="table table-bordered">
          <tbody>
            {% for object in object_list %}
            <tr>
              <td>{{ object }}</td>
              <td><a href="{% url 'category-update' object.id %}"><i
                    class="fa fa-edit"></i></a> 
                    <a
                  href="{% url 'category-delete' object.id %}"><i
                    class="fa fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

    </div>
  </div>


  <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'category-create' %}" method="POST">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add new category</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              {% csrf_token %}

              {% for field in form %}
                  <div class="form-group">
                    {{field.label_tag}}
                    {{ field|add_class:"form-control" }}
                    {{field.help_text}}
                    {{field.errors}}
                  </div>
              {% endfor %}
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

corecode/templates/corecode/form_snippet.html
{% load widget_tweaks %}

{% for field in form %}
<div class="form-group row">
  <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">
    {{ field.label }}
    {% for error in field.errors %}
      <small id="{{ field.auto_id }}" class="text-danger">{{ error }}</small>
    {% endfor %}
  </label>
  <div class="col-sm-9">
    {{ field | add_class:"form-control"}}
    {% if field.help_text %}
    <small>{{ field.help_text|safe }}</small>
    {% endif %}
  </div>
</div>
{% endfor %}

corecode/templates/corecode/mgt_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
  {{title}}
{% endblock title %}


{% block main %}
<div class="container-right">
  <div class="row">
    <div class="col-sm-12">
      <form method="POST">
        {% csrf_token %}

        <div class="mb-3">
          {% for field in form %}
          <div class="form-group">
            {{ field.label_tag}}
            {{ field | add_class:"form-control" |add_error_class:"is-invalid" | attr:"required"}}
            {{field.help_text}}
            {{field.errors}}
          </div>
          {% endfor %}
        </div>


        <input type="submit" value="Save" class="w-25 btn btn-primary">

      </form>
    </div>
  </div>
</div>

{% endblock main %}

corecode/templates/corecode/session_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Set Year
{% endblock title %}


  

{% block main %}
<div class="container-right">
  <br>

<a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal1">
    <i class="fa fa-plus"></i>
    Add new Year
  </a>
  <br>
  <div class="row">
    <div class="col-sm-12">

        <table class="table table-bordered">
          <tbody>
            {% for object in object_list %}
            <tr>
              <td>{{ object }}</td>
              <td>
                {% if object.current == True %}
                  Current <i class="fa fa-check"></i>
                {% endif %}
              </td>
              <td><a href="{% url 'corecode:session-update' object.id %}"><i
                    class="fa fa-edit"></i></a> <a
                  href="{% url 'corecode:session-delete' object.id %}"><i
                    class="fa fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

    </div>
  </div>


  <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'corecode:session-create' %}" method="POST">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add new Year</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            
              {% csrf_token %}

              {% for field in form %}
                  <div class="form-group">
                    {{field.label_tag}}
                    {{ field|add_class:"form-control" }}
                  </div>
              {% endfor %}
            
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

corecode/templates/corecode/siteconfig.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
  {{title}}
{% endblock title %}



{% block title-side %}{% endblock title-side %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ formset.management_form}}

    <div class="mb-3">
      {% for form in formset %}
      <div class="form-group row">
        {{ form.id }}
        <div class="col-2">{{ form.key.value}}</div>
        <div class="col-6">{{ form.value | add_class:"form-control" | attr:"required"}}</div>

        {% if form.errors %}

        {% endif %}

      </div>
      {% endfor %}
    </div>


    <input type="submit" value="Save" class="w-25 btn btn-primary">

  </form>

{% endblock content %}

corecode/templates/corecode/subject_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Subjects
{% endblock title %}


{% block breadcrumb %}
  <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal1">
    <i class="fa fa-plus"></i>
    Add new subject
  </a>
{% endblock breadcrumb %}
  

{% block content %}
  <div class="row">
    <div class="col-sm-12">

        <table class="table table-bordered">
          <tbody>
            {% for object in object_list %}
            <tr>
              <td>{{ object }}</td>
              <td><a href="{% url 'subject-update' object.id %}"><i
                    class="fa fa-edit"></i></a> <a
                  href="{% url 'subject-delete' object.id %}"><i
                    class="fa fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

    </div>
  </div>


  <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'subject-create' %}" method="POST">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add new subject</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              {% csrf_token %}

              {% for field in form %}
                  <div class="form-group">
                    {{field.label_tag}}
                    {{ field|add_class:"form-control" }}
                  </div>
              {% endfor %}
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

corecode/templates/corecode/term_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
Set Month
{% endblock title %} 
  

{% block main %}
<div class="container-right">
  <br>
  <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#modal1">
    <i class="fa fa-plus"></i>
    Add new Month
  </a><br><br>
  <div class="row">
    <div class="col-sm-12">

        <table class="table table-bordered">
          <tbody>
            {% for object in object_list %}
            <tr>
              <td>{{ object }}</td>
              <td>
                {% if object.current == True %}
                  Current <i class="fa fa-check"></i>
                {% endif %}
              </td>
              <td><a href="{% url 'corecode:term-update' object.id %}"><i
                    class="fa fa-edit"></i></a> <a
                  href="{% url 'corecode:term-delete' object.id %}"><i
                    class="fa fa-trash-alt"></i></a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

    </div>
  </div>


  <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{% url 'corecode:term-create' %}" method="POST">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Add new Month</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            
              {% csrf_token %}

              {% for field in form %}
                  <div class="form-group">
                    {{field.label_tag}}
                    {{ field|add_class:"form-control" }}
                  </div>
              {% endfor %}
            
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock main %}