cdc/urls.py
from django.contrib import admin
from django.urls import path,include
import main.urls
import user.urls
import finance.urls
import corecode.urls
import libman.urls

from . import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('finance/',include("finance.urls")),
    path('user/',include("user.urls")),
    path('others/',include("corecode.urls")),
    path('asset',include("asset.urls")),
    path('library',include("libman.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

main/urls.py
from django.urls import path
from main import views

app_name="main"


urlpatterns=[
	path('',views.index,name="index"),

	##########################    STUDENT SECTION         ###########################
	path('newstudent',views.StudentCreateView.as_view(),name="add-student"),
	path('student/<int:pk>/',views.StudentDetail.as_view(),name="student-detail"),
	path('student/<int:pk>/update',views.StudentUpdateView.as_view(),name="student-update"),
	path('students',views.StudentList.as_view(),name="students-list"),
	path('delete/<int:pk>/', views.StudentDeleteView.as_view(), name='student-delete'),




	path('visit/<int:pk>',views.VisitDetail.as_view(),name="visit-detail"),
	
	path('search',views.search,name="search"),
	
	
	path('newvisit',views.NewVisit.as_view(),name="add-homevisit"),
	path('vsearch',views.visit_search,name="visit-search"),
	path('visits',views.VisitList.as_view(),name="visit-list"),
	path('giftallocation',views.GiftAllocation.as_view(),name="gift-allocation"),
	path('giftlist',views.GiftList.as_view(),name="gift-list"),
	path('notifications',views.NotificationList.as_view(),name="not-list"),
	path('message',views.Message.as_view(),name="send-message"),
	path('send_sms',views.send_sms,name="send-sms"),	
	path('updateremarks/<int:pk>',views.UpdateRemarks.as_view(),name="update-remarks"),	
	path('visitclosed/<int:pk>',views.complete,name="visit-close"),	
	path('send_gift_notification',views.send_gift_notification,name="gift-notification"),
	path('createleave',views.LeaveCreate.as_view(),name="leave-create"),
	path('leaves',views.LeaveList.as_view(),name="leave-list"),
	path('leave/<int:pk>',views.LeaveDetail.as_view(),name="leave-detail"),
	path('leaveapprove/<int:pk>',views.approve_leave,name="leave-approve"),
	path('leavereject/<int:pk>',views.reject_leave,name="leave-reject"),
	path('leave_close/<int:pk>',views.close_leave,name="leave-close"),
	path('performance',views.PerformanceCreate.as_view(),name="performance-create"),	
	path('student/<int:pk>/performance',views.student_performance,name="student-performance"),	
	path('visit/<int:pk>/uploadimages',views.VisitImages.as_view(),name="image-upload"),
	path('parent',views.ParentList.as_view(),name="parent-list"),
	path('parent/<int:pk>',views.ParentDetail.as_view(),name="parent-detail"),
	path('parentsearch',views.parent_search,name="parent-search"),
	path('student_download',views.student_download,name="student-download"),
	path('gift/<int:pk>/update',views.UpdateStatus.as_view(),name='update-status'),
	
	path('student/gift',views.StudentGiftList.as_view(),name="student-gift-list"),
	
	
	#path('send_to',views.send_sms_to_specific,name="send-selected"),
	path('send_to',views.Message2.as_view(),name="send-selected"),
	#path('addparent',views.ParentCreate.as_view(),name='parent-create'),



]

main/forms.py
from django import forms
from main.models import *
from django.contrib.auth import get_user_model

class StudentForm(forms.ModelForm):
	class Meta:
		model=Student
		fields=("__all__")
		widgets={
			'reg_number':forms.Textarea(attrs={'col':1,'rows':1}),
			'first_name':forms.Textarea(attrs={'col':1,'rows':1}),
			'second_name':forms.Textarea(attrs={'col':1,'rows':1}),
			'surname':forms.Textarea(attrs={'col':1,'rows':1}),
			'school':forms.Textarea(attrs={'col':1,'rows':1}),			
			'talent':forms.Textarea(attrs={'col':1,'rows':1}),
			'location':forms.Textarea(attrs={'col':1,'rows':1}),
			'date_of_birth':forms.DateInput(attrs={'type':'date'}),
			'date_of_baptism':forms.DateInput(attrs={'type':'date'}),
			'date_of_dedication':forms.DateInput(attrs={'type':'date'}),
			'centre':forms.Textarea(attrs={'col':1,'rows':1}),	
			'village':forms.Textarea(attrs={'col':1,'rows':1}),
			
		}


class VisitForm(forms.ModelForm):
	student=forms.ModelChoiceField( 		
		queryset=Student.objects.all(),
		
		)
	class Meta:
		model=HomeVisit
		fields=['student','date','staff_to_visit']
		widgets={
			'student':forms.Textarea(attrs={'col':1,'rows':1}),
			'date':forms.DateInput(attrs={'type':'date'}),			
		}

class GiftForm(forms.ModelForm):

	class Meta:
		model=Gift
		fields=("__all__")
		widgets={
			'gift_type':forms.Textarea(attrs={'col':1,'rows':1}),
			'student':forms.Textarea(attrs={'col':1,'rows':1}),
			}
class GiftStatusForm(forms.ModelForm):

	class Meta:
		model=Gift
		fields=['status']
	
class MessageForm(forms.ModelForm):
	recipient=forms.ModelChoiceField(
		queryset=Parent.objects.all(),
		#disabled=True,
		widget=forms.HiddenInput,
		)
	class Meta:
		model=Message
		fields=("__all__")
		widgets={
			'recipient':forms.Textarea(attrs={'col':1,'rows':1}),
			}


class MessageForm2(forms.ModelForm):
	recipient=forms.ModelChoiceField(
		queryset=Parent.objects.all(),
		#disabled=True,
		#widget=forms.HiddenInput,
		)

	class Meta:
		model=Message
		fields=("__all__")
		widgets={
			'recipient':forms.Textarea(attrs={'col':1,'rows':1}),
			}


class HomeRemarkForm(forms.ModelForm):
	class Meta:
		model=HomeVisit
		fields=['report']

class HomePhotoForm(forms.ModelForm):
	
	class Meta:
		model=HomevisitImages
		fields=['visit','image']

class HomevisitImagesForm(forms.ModelForm):
	class Meta:
		model=HomevisitImages
		fields=['image','visit']

class LeaveForm(forms.ModelForm):
	
	
	class Meta:
		model=Leave
		fields=['staff','start_date','end_date']
		#fields=("__all__")

		widgets={
			'start_date':forms.DateInput(attrs={'type':'date'}),
			'end_date':forms.DateInput(attrs={'type':'date'}),			
		}

class PerformanceForm(forms.ModelForm):
	class Meta:
		model=Performance
		fields=("__all__")
		widgets={
			'marks':forms.Textarea(attrs={'col':1,'rows':1}),
			'grade':forms.Textarea(attrs={'col':1,'rows':1}),
			'position':forms.Textarea(attrs={'col':1,'rows':1}),
			}

class ParentForm(forms.ModelForm):
	class Meta:
		model=Parent
		fields=("__all__")
		
		widgets={			
			'first_name':forms.Textarea(attrs={'col':1,'rows':1}),
			'second_name':forms.Textarea(attrs={'col':1,'rows':1}),
			'phone_number':forms.Textarea(attrs={'col':1,'rows':1}),
			'occupation':forms.Textarea(attrs={'col':1,'rows':1}),			
			}

main/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q,Sum,Count
from django.http import HttpResponse
from django.forms import modelformset_factory
from django.utils import timezone
from django.conf import settings
from django.urls import reverse_lazy
from django.forms import widgets
from twilio.rest import Client
from twilio import *
import numpy as np



# Create your views here.
from main.models import *
from main.forms import*
from finance.models import Invoice
import csv



@login_required
def siteconfig_view(request):
  """ Site Config View """
  if request.method == 'POST' :
    form = SiteConfigForm(request.POST,request.FILES)
    if form.is_valid():
      form.save()
      messages.success(request, 'Configurations successfully updated')
      return HttpResponseRedirect('site-config')
  else:
    form = SiteConfigForm(queryset=SiteConfig.objects.all())

  context = {"formset": form, "title": "Configuration"}
  return render(request, 'main/siteconfig.html', context)



@login_required
def index(request):
	template_name='base.html'
	notice=Notification.objects.filter(notification_date=datetime.date.today())
	number_of_notifications=notice.count()
	user_approved=Leave.objects.filter((Q(staff=request.user))&(Q(status='approved')))
	user_rejected=Leave.objects.filter((Q(staff=request.user))&(Q(status='rejected')))
	teacher_per_class=Student.objects.filter(teacher=request.user)
	teacher_per_class_count=Student.objects.filter(teacher=request.user).count()
	order_list=Leave.objects.filter(status='not_approved')
	ctc={'teacher_per_class_count':teacher_per_class_count,'teacher_per_class':teacher_per_class,'user_rejected':user_rejected,'notice':notice,'number_of_notifications':number_of_notifications,'user_approved':user_approved,'order_list':order_list}	
	return render(request,template_name,ctc)
@login_required
def search(request):
	template_name='main/search.html'
	if request.method=='GET':
		query=request.GET.get('q')
		submitbutton=request.GET.get('submit')

		if query is not None:
			results=Student.objects.filter(Q(reg_number__icontains=query)|Q(first_name__icontains=query)|Q(second_name__icontains=query))
			return render(request,template_name,{'results':results,'submitbutton':submitbutton})
		else:
			return render(request,template_name)
@login_required
def visit_search(request):
	template_name='main/visit-search.html'
	if request.method=='GET':
		query=request.GET.get('q')
		submitbutton=request.GET.get('submit')

		if query is not None:
			results=HomeVisit.objects.filter(Q(date__icontains=query)|Q(status__icontains=query))
			return render(request,template_name,{'results':results,'submitbutton':submitbutton})
		else:
			return render(request,template_name)


class StudentCreateView(SuccessMessageMixin,LoginRequiredMixin, CreateView):
  form_class = StudentForm
  template_name = 'main/mgt_form.html'
  success_url = reverse_lazy('student-list')
  success_message = 'Student successfully added'

  def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['title'] = 'Add new New Student'
      return context

class StudentDetail(LoginRequiredMixin,DetailView):
	model=Student

	def get_context_data(self, **kwargs):
		context = super(StudentDetail, self).get_context_data(**kwargs)
		context['payments'] = Invoice.objects.filter(student=self.object)
		return context
		

class StudentUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Student
    form_class=StudentForm
	
    success_message = "Record successfully updated."
    success_url = reverse_lazy('main:students-list')
    template_name='main/student_update.html'

    
class StudentList(LoginRequiredMixin,ListView):
	model=Student

class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('main:students-list')



class VisitDetail(LoginRequiredMixin,DetailView):
	model=HomeVisit
	def visit_image_form(self):
		if self.request.user.is_authenticated:
			return HomevisitImagesForm()
		return None

	def get_parent_number(self):
		if self.request.method=='POST':
			query=request.POST.get('student')
			parent=HomeVisit.objects.filter(student=1)
			number=parent.phone_number
			return number

		

	def get_context_data(self,*args,**kwargs):
		context=super().get_context_data(**kwargs)
		context['closed']=HomeVisit.objects.filter(Q(id=self.object.id)&Q(status="ongoing")&Q(staff_to_visit=self.request.user)) 
		context['image_form']=self.visit_image_form()
		context['number']=self.get_parent_number()
		return context

class VisitList(LoginRequiredMixin,ListView):
	model=HomeVisit


	
class NewStudent(LoginRequiredMixin,CreateView):
	form_class=StudentForm
	template_name='main/student-add.html'
	model=Student

	def form_valid(self,request):
		if self.request.method=='POST':
			form=StudentForm(self.request.POST,self.request.FILES)
			if form.is_valid():
				form.save()
				#return HttpResponse("Gift Saved succesfully")
			return render(request,self.template_name,{'form':form})
		else:
			form=StudentForm()
			return render(request,self.template_name)

class NewVisit(LoginRequiredMixin,CreateView):
	form_class=VisitForm
	template_name='main/homevisit-add.html'

	def form_valid(self,request):
		if self.request.method=='POST':
			form=VisitForm(self.request.POST,self.request.FILES)
			if form.is_valid():
				form.save()
				return HttpResponse("HomeVist scheduled added succesfully")
			return render(request,self.template_name,{'form':form})
		else:
			form=VisitForm()
			return render(request,self.template_name)


class VisitImages(LoginRequiredMixin,CreateView):
	form_class=HomePhotoForm
	template_name='main/update_homevisit2.html'

	def get_initial(self):
		initial=super().get_initial()
		initial['visit']=self.kwargs["pk"]
		return initial


	def form_valid(self,request):
		if self.request.method=='POST':
			form=HomePhotoForm(self.request.POST,self.request.FILES)
			if form.is_valid():
				form.save()	
				return redirect('main:visit-list')			
			return render(request,self.template_name,{'form':form})
		else:
			form=HomePhotoForm()
			return render(request,self.template_name)


	def get_context_date(self,*args,**kwargs):
		context=super().get_context_data(**kwargs)
		context['visit']=self.get_initial()
		return context

	def get_absolute_url(self):
		return reverse('main:visit-detail',kwargs={'pk':self.id})

class GiftAllocation(LoginRequiredMixin, CreateView):
    model = Gift
    fields = ['student','gift_type','status']
    success_url = reverse_lazy('main:gift-list')
    template_name='main/gift_allocation.html'

    def get_initial(self):
    	initial=super().get_initial()
    	initial['student']= Student.objects.get(pk=self.request.GET['student'])
    	return initial

    def form_valid(self,request):
    	if self.request.method=='POST':
    		form=GiftForm(self.request.POST)
    		if form.is_valid():
    			form.save()
    			return redirect('main:gift-list')
    		return render(request,self.template_name,{'form':form})	

    def send_sms_to_parent(self):
    	parent=Parent.objects.filter(student=student)
    	number=Parent.phone_number
    	mytwilionum="+12072227121"
    	client=Client(settings.TWILIO_ACCOUNT_SID,settings.TWILIO_AUTH_TOKEN)
    	client.messages.create(
    		to=number,
    		from_=mytwilionum,
    		body="Mzazi unaombwa uje kuchukua zawadi ya mtoto"

    		)
  
    def get_context_data(self, **kwargs):
        context = super(GiftAllocation, self).get_context_data(**kwargs)
        student = Student.objects.get(pk=self.request.GET['student'])
        context['student'] = student
        context['student']=self.get_initial()  
        #context['form']=self.form_valid()           
        return context


class GiftList(LoginRequiredMixin,ListView):
	model=Gift
class StudentGiftList(ListView):
	model=Student	
	template_name='main/giftallocation.html'

	def get_all(self):
		all_student=Student.objects.all()
		return all_student

	def get_context_data(self, **kwargs):
		context=super().get_context_data(**kwargs)		
		context['all_student']=self.get_all()
		return context	
	


class NotificationList(LoginRequiredMixin,ListView):
	model=Notification

class Message(LoginRequiredMixin,CreateView):
	form_class=MessageForm
	template_name='base.html'

	def get_initial(self):
		ss=Parent.objects.all()
		for everys in ss:
			return {'recipient':everys}


	def form_valid(self,request):
		if self.request.method=='POST':
			form=MessageForm(self.request.POST)
			if form.is_valid():	
				note="Message has been sent"			
				form.save()				
				return redirect("/")
			return render(request,self.template_name,{'form':form,'note':note})
		else:
			form=MessageForm()
			return render(request,self.template_name)

class Message2(LoginRequiredMixin,CreateView):
	form_class=MessageForm2
	template_name='main/message_centre.html'

	#def get_initial(self):
		#ss=Parent.objects.all()
		#for everys in ss:
			#return {'recipient':everys}


	def form_valid(self,request):
		if self.request.method=='POST':
			form=MessageForm2(self.request.POST)
			if form.is_valid():	
				note="Message has been sent"			
				form.save()				
				return redirect("/")
			return render(request,self.template_name,{'form':form,'note':note})
		else:
			form=MessageForm2()
			return render(request,self.template_name)

@login_required
def send_gift_notification(request):
	template_name='base.html'
	mytwilionum="+12072227121"
	client=Client(settings.TWILIO_ACCOUNT_SID,settings.TWILIO_AUTH_TOKEN)	
	allparent=Parent.objects.all()
	client.messages.create(
				to="+254704478977",
				from_=mytwilionum,
				body="Dear Parent Kindly come and Collect The Gift of your student"
				)

main/templates/main/homevisit-add.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}


{%block content%}

	<div class="container-right">
		<form method="POST">
			{% csrf_token %}
			{{form|crispy}}

			<button class="btn btn-primary" type="submit">Create HomeVisit</button>
			
		</form>
	</div>
		
{%endblock%}

main/templates/main/leave_detail.html
{%extends 'base.html'%}
{%load crispy_forms_tags%}

{%block title%}
{%endblock%}

{%block main%}
    <div class="container-right">
    	<div class="card-header">
	       		<h5 class="text-center">{{object}} </h5>
	     </div>
	<table style="width: 90%">
		<tr>
			<th>FROM STAFF</th>
			<th>START DATE</th>
			<th>END DATE</th>						
			<th>STATUS</th>
			<th>DAYS REQUESTED</th>
			<th>TOTAL TAKEN</th>	
			<th>DAYS REMAINING</th>		
		</tr>
		<tr>
			<td>{{object.staff}}</td>
			<td>{{object.start_date}}</td>
			<td>{{object.end_date}}</td>
			<td>{{object.status}}</td>				
			<td>{{object.number_of_days}}</td>
			<td>{{object.total_taken_days}}</td>	
			<td>{{object.remaining_days}}</td>	
						
		</tr>		
	</table>

	
			
	<br>
	{% if leaves %}
	<p class="btn btn-primary">Leave closed</p>

	{%else%}
	{% if perms.main.can_approve_leave %}
		<a class="btn btn-primary" href="{% url 'main:leave-approve' leave.id%}">Approve</a>&nbsp;&nbsp;&nbsp;&nbsp;
		<a class="btn btn-primary" href="{% url 'main:leave-reject' leave.id%}">Reject</a>&nbsp;&nbsp;&nbsp;&nbsp;
	{% endif %}
	{% endif %}


	</div>
	


{%endblock%}

main/templates/main/leave_list.html
{%extends 'base.html'%}

{%block content%}
	<div class="container-right">
		<div class="card-header">
	       		<h5 class="text-center" >{{user}} Leave Report </h5>
	      </div>
	      <h1>Current Remaining Days:{% for prod in single_user %}{{prod.remaining_days}}{% endfor %}</h1><br>
	      	<table style="width: 90%">
					<tr>
						<th>START DATE</th>
						<th>END DATE</th>
						<th>STATUS</th>
						<th>NUMBER OF DAYS TAKEN</th>
						<th>TOTAL TAKEN</th>
						<th>REMAINING DAYS</th>
						<th>STAFF_LIST</th>
										
						                
					</tr>
						 {% for prod in single_user %}
					<tr  class='clickable-row' data-href="{% url 'main:leave-detail' prod.id %}">       
							        
						<td>{{prod.start_date}}</td>       
						<td>{{prod.end_date}}</td>
						<td>{{prod.status}}</td>
						<td>{{prod.number_of_days}}</td>
						<td>{{prod.total_taken_days}}</td>
						<td>{{prod.remaining_days}}</td>
						<td>{{prod.staff}}</td>
								
						
						                             
					</tr>		    
						{% endfor %}
				</table>      
		
	</div>
{%endblock%}

main/templates/main/message_centre.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}

	<div class="container-right">
		<div class="card-header">
	       		<h5 class="text-center">Message Centre </h5>
	    </div>

	    <form method="POST">
	    	{% csrf_token %}
	    	{{form|crispy}}

	    	<button class="btn btn-primary">
	    		Send 
	    	</button>
	    	
	    </form>


	    <!--<form method="GET">
			 <div class="form-group">
			    <label for="numbers">Phone Numbers:</label>
			    <input type="" class="form-control" placeholder="Enter phone numbers separted by a comma" multiple>
			   
			 </div>
			 <div class="form-group">
			    <label for="message">Message</label>
			    <textarea  name="message"  class="form-control" rows="7"> 

			    </textarea>
			 </div>
			  
			  
			  <button type="submit" class="btn btn-primary">Send</button>
		</form>-->			
	    	
		
	</div>
{% endblock %}

main/templates/main/notification_list.html
{%extends 'base.html'%}

{%block main%}
	<div class="container-right">
		<div class="card-header">
	       		<h5 class="text-center">ALL Notification  </h5>
	      	</div>
	      	<table style="width: 90%">
					<tr>
						<th>STUDENT</th>
						<th>ISSUE</th>
						<th>DETAIL</th>
						<th>DATE</th>				
						                
					</tr>
						 {% for prod in object_list %}
					<tr>       
						<td><a href="{% url 'main:visit-detail' prod.id %}">{{prod.id}}</a></td>	        
						<td>{{prod.student}}</td>        
						<td>{{prod.topic}}</td>
						<td>{{prod.detail}}</td>
						<td>{{prod.notification_date}}</td>			
						
						                             
					</tr>		    
						{% endfor %}
				</table>      
		
	</div>
{%endblock%}

main/templates/main/p_search.html
{%extends 'base.html'%}
{%block main%}
<div class="container-right">
    <h5>Enter Parent Detail</h5><br>
	<form method="GET" >
		<input class="sinput" type="text" name="q" value="{{request.GET.q}}" placeholder="Search in student">
			 <br>
			 <br>
		 <button class="btn btn-primary" type="submit" value="Search" name="submit">Search</button>
	</form>
	<br>
		{% if submitbutton == 'Search' and request.GET.q != '' %}
		{%if results%}
		<ul>
			{%for result in results %}
				<li>
					<a href="{% url 'main:parent-detail' result.id %}"><h2>{{result.first_name}} {{result.surname_name}} {{result.second_name}} </h2></a>			
				</li>
			{%endfor%}			
		</ul>
		{%else%}
		<br>
		<br>
		<h4>No Student Found!!!</h4>
		{%endif%}
		{%endif%}
</div>
{%endblock%}

main/templates/main/perfomance.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block main %}
	
	<div class="container-right">
		<div class="card-header">
	       <h5 class="text-center">Create Performance of the student </h5>
	 </div>
		<form method="POST">
			{% csrf_token %}
			{{form|crispy}}


			<button class="btn btn-primary" type="submit">SUBMIT</button>
			
		</form>
			
		
	</div>
{% endblock %}

main/templates/main/siteconfig.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
  {{title}}
{% endblock title %}



{% block title-side %}{% endblock title-side %}

{% block content %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ formset.management_form}}

    <div class="mb-3">
      {% for form in formset %}
      <div class="form-group row">
        {{ form.id }}
        <div class="col-2">{{ form.key.value}}</div>
        <div class="col-6">{{ form.value | add_class:"form-control" | attr:"required"}}</div>

        {% if form.errors %}

        {% endif %}

      </div>
      {% endfor %}
    </div>


    <input type="submit" value="Save" class="w-25 btn btn-primary">

  </form>

{% endblock content %}

main/templates/main/student-add.html
{%extends 'base.html'%}
{% load crispy_forms_tags %}

{%block main%}
	<div class="container-right">
		<form method="POST" enctype="multipart/form-data">
			{%csrf_token%}
			{{form|crispy}}
			<button class="btn btn-primary" type="submit">ADD STUDENT</button>			
		</form>
			
		
	</div>
{%endblock%}

main/templates/main/student_list.html
{% extends 'base.html' %}


{% block title %}Students{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'main:add-student' %}"><i
    class="fas fa-plus"></i> New Student</a>

{% endblock breadcrumb %}


{% block content %}


  <div class="table-responsive">
    <table id="studenttable" class="table table-bordered table-hover" data-page-length='100'>
      <thead class="thead-light">
        <tr>
          <th>Student</th>
          <th>Number</th>         
          <th>Parent</th>
          <th>Location</th>         
          <th>Village</th>
          <th>Gender</th>
          <th>Sponsor</th>
         
        </tr>
      </thead>
      <tbody>

       	 {% for prod in object_list %}
					<tr class='clickable-row' data-href="{% url 'main:student-detail' prod.id %}">       
						<td>{{prod.first_name}} {{prod.surname}} {{prod.second_name}}</td>	
						<td>{{prod.reg_number}}</td>
						<td>{{prod.parent}}</td>       
						<td>{{prod.location}}</td>					
						<td>{{prod.village}}</td>
						<td>{{prod.gender}}</td>
						<td>{{prod.sponsor_status}}</td>

						
						                             
					</tr>		    
						{% endfor %}

      </tbody>
    </table>
    <a href="{% url 'main:student-download' %}">Download the Report</a>    	
  </div>

{% endblock content %}


{% block morejs %}
<script>
  $('#studenttable').DataTable({
  });
</script>

{% endblock morejs %}

main/templates/main/student_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	<div class="container-right">
		<div class="card-header">
	       		<h5 class="text-center">Update details for student {{object}} </h5>
	     </div>
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{{form|crispy}}

			<button class="btn btn-primary" type="SUBMIT">
				update
			</button>
			
		</form>
			
		
	</div>
{% endblock content %}

main/templates/main/update_homevisit.html
{%extends 'base.html'%}
{% load crispy_forms_tags%}

{%block content %}
	<div class="container-right">

		<form method="POST">
			{%csrf_token %}
		
			{{form|crispy}}
		

			<button class="btn btn-primary" type="submit">SAVE</button>
		
	</form>
		
	</div>
{%endblock%}

main/templates/main/update_homevisit2.html
{%extends 'base.html'%}
{% load crispy_forms_tags%}

{%block content %}
	<div class="container-right">
		<h2>Upload Images for the {{object}} Homevisit</h2>

		<form method="POST" enctype="multipart/form-data">
			{%csrf_token %}
		
			{{form|crispy}}
		

			<button class="btn btn-primary" type="submit">SAVE</button>
		
	</form>
		
	</div>
{%endblock%}

main/templates/main/visit-search.html
{%extends 'base.html'%}
{%block main%}
<div class="container-right">
    <h5>HomeVisit Detail</h5><br>
	<form method="GET" >
		<input class="sinput" type="text" name="q" value="{{request.GET.q}}" placeholder="Search in student">
			 <br>
			 <br>
		 <button class="btn btn-primary" type="submit" value="Search" name="submit">Search</button>
	</form>
	<br>
		{% if submitbutton == 'Search' and request.GET.q != '' %}
		{%if results%}
		<ul>
			{%for result in results %}
				<li>
					<a href="{% url 'main:visit-detail' result.id %}"><h2>Visit to {{result.student}} on {{result.date}} conducted by {{result.staff_to_visit}} </h2></a>			
				</li>
			{%endfor%}			
		</ul>
		{%else%}
		<br>
		<br>
		<h4>No Such Visits Found!!!</h4>
		{%endif%}
		{%endif%}
</div>
{%endblock%}