cdc/urls.py
from django.contrib import admin
from django.urls import path,include
import main.urls
import user.urls
import finance.urls
import corecode.urls
import libman.urls

from . import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main.urls")),
    path('finance/',include("finance.urls")),
    path('user/',include("user.urls")),
    path('others/',include("corecode.urls")),
    path('asset',include("asset.urls")),
    path('library',include("libman.urls"))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATICFILES_DIRS)

finance/urls.py
from django.urls import path

from .views import download_expense_report, download_finance_report, ExpenseList,ExpenseCreate,InvoiceCreateView, InvoiceListView, InvoiceDeleteView, InvoiceDetailView,InvoiceUpdateView,ReceiptCreateView, ReceiptUpdateView, bulk_invoice
app_name='finance'
urlpatterns = [
    path('list/', InvoiceListView.as_view(), name='invoice-list'),
    path('create/', InvoiceCreateView.as_view(), name='invoice-create'),
    path('<int:pk>/detail/', InvoiceDetailView.as_view(), name='invoice-detail'),
    path('<int:pk>/update/', InvoiceUpdateView.as_view(), name='invoice-update'),
    path('<int:pk>/delete/', InvoiceDeleteView.as_view(), name='invoice-delete'),
    path('receipt/create', ReceiptCreateView.as_view(), name='receipt-create'),
    path('receipt/<int:pk>/update/', ReceiptUpdateView.as_view(), name='receipt-update'),

    path('bulk-invoice/',  bulk_invoice, name='bulk-invoice'),
    path('expenses',ExpenseList.as_view(),name="expense-list"),
	path('expense_add',ExpenseCreate.as_view(),name="expenses-create"),
    path('report_download',download_finance_report,name='finance-report'),
    path('expense_download',download_expense_report,name='expense-report'),
]

finance/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
import datetime

from corecode.models import StudentClass, AcademicSession, AcademicTerm,ExpenseCategory
from main.models import Student

class Invoice(models.Model):
  student = models.ForeignKey(Student, on_delete=models.CASCADE)
  year = models.ForeignKey(AcademicSession, on_delete=models.CASCADE)
  month = models.ForeignKey(AcademicTerm, on_delete=models.CASCADE)
  balance_from_previous_term = models.IntegerField(default=0)
  status = models.CharField(max_length=20, choices=[(
      'active', 'Active'), ('closed', 'Closed')], default='active')

  class Meta:
    ordering = ['student', 'month']

  def __str__(self):
    return f'{self.student}'


  def balance(self):
    payable = self.total_amount_payable()
    paid = self.total_amount_paid()
    return payable - paid

  def amount_payable(self):
    items = InvoiceItem.objects.filter(invoice=self)
    total = 0
    for item in items:
      total += item.amount
    return total

  def total_amount_payable(self):
    return self.balance_from_previous_term + self.amount_payable()

  def total_amount_paid(self):
    receipts = Receipt.objects.filter(invoice=self)
    amount = 0
    for receipt in receipts:
      amount += receipt.amount_paid
    return amount

  def get_absolute_url(self):
    return reverse('invoice-detail', kwargs={'pk': self.pk})


class InvoiceItem(models.Model):
  invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
  description = models.CharField(max_length=200)
  amount = models.IntegerField()


class Receipt(models.Model):
  invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
  amount_paid = models.IntegerField()
  date_paid = models.DateField(default=timezone.now)
  comment = models.CharField(max_length=200, blank=True)

  def __str__(self):
    return f'Receipt on {self.date_paid}'

class Expense(models.Model):  
  category=models.ForeignKey(
    to="corecode.ExpenseCategory",
    on_delete=models.SET_NULL,
    null=True
    )
  amount=models.IntegerField()
  date_incurred=models.DateField(default=datetime.date.today)
  
  def __str__(self):
    return '{}'.format(self.category)

finance/forms.py
from django.forms import inlineformset_factory, modelformset_factory

from corecode.models import AcademicSession, AcademicTerm, StudentClass
from .models import Invoice, InvoiceItem, Receipt,Expense
from django import forms
InvoiceItemFormset = inlineformset_factory(
    Invoice, InvoiceItem, fields=['description', 'amount'], extra=1, can_delete=True)

InvoiceReceiptFormSet = inlineformset_factory(
    Invoice, Receipt, fields=('amount_paid', 'date_paid', 'comment'), extra=0, can_delete=True
)

Invoices = modelformset_factory(Invoice, exclude=(), extra=4)


		
class ExpenseForm(forms.ModelForm):
	class Meta:
		model=Expense
		fields=("__all__")
		widgets={			
			'date_incurred':forms.DateInput(attrs={'type':'date'}),

		}

finance/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.forms import widgets
from django.urls import reverse_lazy
from django.http import HttpResponse
import csv


from main.models import Student
from .models import Invoice, InvoiceItem, Receipt,Expense
from .forms import InvoiceItemFormset, InvoiceReceiptFormSet, Invoices,ExpenseForm

class InvoiceListView(LoginRequiredMixin, ListView):
  model = Invoice


class InvoiceCreateView(LoginRequiredMixin, CreateView):
    model = Invoice
    fields = '__all__'
    success_url = '/finance/list'

    def get_context_data(self, **kwargs):
        context = super(InvoiceCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['items'] = InvoiceItemFormset(
                self.request.POST, prefix='invoiceitem_set')
        else:
            context['items'] = InvoiceItemFormset(prefix='invoiceitem_set')
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['items']
        self.object = form.save()
        if self.object.id != None:
            if form.is_valid() and formset.is_valid():
                formset.instance = self.object
                formset.save()
        return super().form_valid(form)


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    model = Invoice
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(InvoiceDetailView, self).get_context_data(**kwargs)
        context['receipts'] = Receipt.objects.filter(invoice=self.object)
        context['items'] = InvoiceItem.objects.filter(invoice=self.object)
        return context


class InvoiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Invoice
    fields = ['student', 'session', 'term',
              'class_for', 'balance_from_previous_term']

    def get_context_data(self, **kwargs):
        context = super(InvoiceUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
          context['receipts'] = InvoiceReceiptFormSet(
              self.request.POST, instance=self.object)
          context['items'] = InvoiceItemFormset(
              self.request.POST, instance=self.object)
        else:
          context['receipts'] = InvoiceReceiptFormSet(instance=self.object)
          context['items'] = InvoiceItemFormset(instance=self.object)
        return context

    def form_valid(self, form):
      context = self.get_context_data()
      formset = context['receipts']
      itemsformset = context['items']
      if form.is_valid() and formset.is_valid() and itemsformset.is_valid():
        form.save()
        formset.save()
        itemsformset.save()
      return super().form_valid(form)



class InvoiceDeleteView(LoginRequiredMixin, DeleteView):
    model = Invoice
    success_url = reverse_lazy('invoice-list')


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    fields = ['amount_paid', 'date_paid', 'comment']
    success_url = reverse_lazy('invoice-list')

    def form_valid(self, form):
        obj = form.save(commit=False)
        invoice = Invoice.objects.get(pk=self.request.GET['invoice'])
        obj.invoice = invoice
        obj.save()
        return redirect('finance:invoice-list')

    def get_context_data(self, **kwargs):
        context = super(ReceiptCreateView, self).get_context_data(**kwargs)
        invoice = Invoice.objects.get(pk=self.request.GET['invoice'])
        context['invoice'] = invoice
        return context


class ReceiptUpdateView(LoginRequiredMixin, UpdateView):
    model = Receipt
    fields = ['amount_paid', 'date_paid', 'comment']
    success_url = reverse_lazy('invoice-list')


class ReceiptDeleteView(LoginRequiredMixin, DeleteView):
    model = Receipt
    success_url = reverse_lazy('invoice-list')

@login_required
def bulk_invoice(request):
    return render(request, 'finance/bulk_invoice.html')


class ExpenseList(ListView):
    model=Expense


class ExpenseCreate(CreateView):
    form_class=ExpenseForm
    template_name='finance/expense_create.html'

    def form_valid(self,request):
        if self.request.method=='POST':
            form=ExpenseForm(self.request.POST)
            if form.is_valid():
                form.save()
                return HttpResponse("expense added ")
            return render(request,self.template_name,{'form':form})
        else:
            form=ExpenseForm()


def download_finance_report(request):  
    response=HttpResponse(content_type='text/csv')
    response['Content-Disposition']='attachment;filename="finance_report.csv"'
    report=Invoice.objects.all()
    writer=csv.writer(response)
    writer.writerow(['STUDENT','ACADEMIC_YEAR','TERM','TOTAL_PAYABLE','TOTAL PAID',' BALANCE'])

    for rows in report:
        writer.writerow([rows.student,rows.year,rows.month,rows.total_amount_payable() ,rows.total_amount_paid(),rows.balance()])

    return response


def download_expense_report(request):  
    response=HttpResponse(content_type='text/csv')
    response['Content-Disposition']='attachment;filename="expense_report.csv"'
    report=Expense.objects.all()
    writer=csv.writer(response)
    writer.writerow(['CATEGORY','AMOUNT','DATE'])

    for rows in report:
        writer.writerow([rows.category,rows.amount,rows.date_incurred])

    return response

finance/templates/finance/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{{ school_name | default:"MySchool" }}</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet"
    href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/Datatables/datatables.min.css' %}" />
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700"
    rel="stylesheet">
</head>

<body
  class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i
              class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'home' %} " class="nav-link"><i class="fa fa-home"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'current-session' %}" class="nav-link">Session: {{ current_session }}</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'current-session' %}" class="nav-link">Term: {{ current_term }}</a>
        </li>
      </ul>



      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <a href="#" class="dropdown-item">
              <i class="fas fa-user mr-2"></i> Profile
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="fas fa-sign-out"></i> Sign out
            </a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-widget="control-sidebar" data-slide="true"
            href="#" role="button"><i class="fas fa-th-large"></i></a>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="{% url 'home' %}" class="brand-link">{{ school_name | default:"MySchool" }}</a>

      <!-- Sidebar -->
      <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column"
            data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item">
              <a href="{% url 'student-list' %}" class="nav-link">
                <i class="nav-icon fas fa-graduation-cap"></i>
                <p>
                  Students
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'staff-list' %}" class="nav-link">
                <i class="nav-icon fas fa-users"></i>
                <p>
                  Member of Staff
                </p>
              </a>
            </li>

            <li class="nav-header">Finance</li>
            <li class="nav-item">
              <a href="{% url 'finance:invoice-list' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  Invoices
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'expenses-create' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  Expenses Add
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'expense-list' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  Expenses report
                </p>
              </a>
            </li>
            <li class="nav-header">Results</li>
            <li class="nav-item">
              <a href="{% url 'create-result' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  Create Results
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'edit-results' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  Update Results
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'view-results' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                  View Results
                </p>
              </a>
            </li>

            <li class="nav-header">Others</li>
            <li class="nav-item has-treeview">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-copy"></i>
                <p>
                  Management
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'sessions' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>
                      Sessions
                    </p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'terms' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>
                      Terms
                      <i class="right"></i>
                    </p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'subjects' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>
                      Subjects
                    </p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'classes' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>
                      Classes
                    </p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'category' %}" class="nav-link">
                    <i class="nav-icon fas fa-bars"></i>
                    <p>
                      Expense Type
                    </p>
                  </a>
                </li>
              </ul>
            </li>
              </ul>
              
            <li class="nav-item">
              <a href="{% url 'configs' %}" class="nav-link">
                <i class="nav-icon fas fa-cog"></i>
                <p>
                  Settings
                </p>
              </a>
            </li>


          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-1">
            <div class="col-sm-8">
              <h1>{% block title %}{% endblock title %}</h1>
            </div>
            <div class="col-sm-4">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">{% block breadcrumb %}{% endblock breadcrumb %}</li>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              {% block fullcard %}
               <p><b>welcome {{user}}</b></p>
              <div class="card">
                {% block content-header %}{% endblock content-header %}
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      {% block content %}


                      {% endblock content %}
                    </div>
                  </div>
                  <!-- /.row -->
                </div>
                <!-- ./card-body -->

              </div>
              {% endblock fullcard %}
              <!-- /.card -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->


  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <!-- jQuery -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'dist/js/jquery.formset.js' %}"> </script>
  <!-- Bootstrap -->
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
  <!-- overlayScrollbars -->
  <script
    src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>

  <!-- AdminLTE App -->
  <script src="{% static 'dist/js/adminlte.js' %}"></script>

  <!-- OPTIONAL SCRIPTS -->
  <script src="{% static 'dist/js/demo.js' %}"></script>

  {% if messages %}
  {% for message in messages %}
  <script type=text/javascript>
    toastr.options.progressBar = true;
    toastr.{{ message.tags }}('{{ message }}')
  </script>
  {% endfor %}
  {% endif %}

  <script src="{% static 'plugins/Datatables/datatables.min.js' %}"></script>

  <script>
    (function ($) {
      $('.clickable-row').css('cursor', 'pointer');
      $(".clickable-row").click(function () {
        window.location = $(this).data("href");
      });
    })(jQuery)

  </script>

  {% block morejs %}

  {% endblock morejs %}



</body>

</html>

finance/templates/finance/invoice_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete invoice "{{ object }}"?</p>
    <p>All receipts attached to this invoice will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

finance/templates/finance/invoice_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}

<div class ="container-right">
  <div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Print</a>
   
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <h3>{{ object }} </h3>
    <h5>{{ object.session }} </h5>
    <h5>{{ object.term }} </h5>
    <h5>{{ object.class_for }} </h5>
    <h6>Status: {{ object.get_status_display }} </h6>
    <hr>
    <div>
      <h4>Expected Balance: {{ object.balance | intcomma }}</h4>
    </div>
  </div>
  <div class="col-sm-8">
    <table class="table table-sm table-bordered">
      Invoice Breakdown</br>
      <thead class="thead-light">
        <tr>
          <th>S/N</th>
          <th>Description</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td>{{ forloop.counter }} </td>
          <td>{{ item.description }} </td>
          <td>{{ item.amount }} </td>
        </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <td></td>
          <td>Total Amount this term</td>
          <td>{{ object.amount_payable | intcomma}}</td>
        </tr>
        <tr>
          <td></td>
          <td>Balance from previous term</td>
          <td>{{ object.balance_from_previous_term | intcomma }}</td>
        </tr>
        <tr>
          <td></td>
          <td>Total Amount Payable</td>
          <td>{{ object.total_amount_payable | intcomma}}</td>
        </tr>
        <tr>
          <td></td>
          <td>Total Amount Paid</td>
          <td>{{ object.total_amount_paid | intcomma}}</td>
        </tr>

      </tfoot>
    </table>
  </div>
</div>

<hr>

<h5>Payment History</h5>
<table class="table table-bordered table-sm">
  <thead class="thead-light">
    <tr>
      <th>S/N</th>
      <th>Amount Paid</th>
      <th>Date Paid</th>
      <th>Comment Paid</th>
    </tr>
  </thead>
  <tbody>
    {% for receipt in receipts %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{ receipt.amount_paid}}</td>
      <td>{{ receipt.date_paid}}</td>
      <td>{{ receipt.comment}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>


{% endblock main %}

finance/templates/finance/invoice_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}

{% if object %}
Update invoice {{ object }}
{% else %}
Add new invoice
{% endif %}

{% endblock title %}


{% block content %}
<div class="container-right">

<form method="POST">
  {% csrf_token %}

  <div class="row">
    <div class="col-sm-6">
      {% for field in form %}
      <div class="form-group row">
        <label class="col col-form-label" for="{{ field.auto_id }}">
          {{ field.label }}
          {% for error in field.errors %}
          <small id="{{ field.auto_id }}" class="text-danger">{{ error }}</small>
          {% endfor %}
        </label>
        <div class="col">
          {{ field | add_class:"form-control"}}
          {% if field.help_text %}
          <small>{{ field.help_text|safe }}</small>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="col-sm-6 callout callout-info">
      {{ items.management_form }}
      <div class="text-center">FEE STRUCTURE</div>
      <div class="row">
        <div class="col"><strong>Fee Type</strong></div>
        <div class="col"><strong>Amount</strong></div>
      </div>
      {% for item in items %}
      <div class="form-group row items-group">
        {{ item.id}}
        <div class="col">{{ item.description | add_class:"form-control"}}</div>
        <div class="col">{{ item.amount | add_class:"form-control"}}</div>
      </div>
      {% endfor %}
    </div>
  </div>


  {% if object %}
    <h4>RECEIPTS</h4>
    <table class="table table-sm">
      {{ receipts.management_form }}
      <thead class="thead-light">
        <tr>
          <th>Amount Paid</th>
          <th>Date Paid</th>
          <th>Comment</th>
          <th><i class="fa fa-trash"></i></th>
        </tr>
      </thead>
      <tbody>
        {% for receipt in receipts %}
        {% for hidden in receipt.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        <tr>
          {% for field in receipt.visible_fields %}
          <td>{{ field | add_class:"form-control form-control-sm"}}</td>
          {% endfor %}
        </tr>
        {% endfor %}

      </tbody>
    </table>
  {% endif %}

  {% if object %}
  <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
  <input type="submit" class="btn btn-primary" value="Create Monthly Contribution">
  {% endif %}
</form>

<hr>

</div>
{% endblock content %}

{% block morejs %}
<script>
  $(".items-group").formset(
    {
      prefix: '{{ items.prefix }}',
      deleteText: "<div class='btn btn-danger btn-circle'><i class='fas fa-trash'></i></div>",
      addText: "<div class='btn btn-success btn-circle'><i class='fas fa-plus'></i></div>"
    }
  )
</script>
{% endblock morejs %}

finance/templates/finance/invoice_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}invoices{% endblock title %}



{% block content %}
<div class="container-right">


<a class="btn btn-primary" href="{% url 'finance:finance-report' %}"><i
    class="fas fa-download"></i>Finance Report</a>
  <br>
  <br>

  <div class="table-responsive">
    <table id="invoicetable" class="table table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th>S/N</th>
          <th>Student</th>
          <th>Year</th>
          <th>Month</th>
          <th>To pay</th>
          <th>Total Paid</th>
          <th>Balance</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        {% for invoice in object_list %}
          <tr class='clickable-row' data-href="{% url 'finance:invoice-detail' invoice.id %}">
            <td>{{ forloop.counter}}</td>
            <td>{{ invoice}}</td>
            <td>{{ invoice.year}}</td>
            <td>{{ invoice.month}}</td>
            <td>{{ invoice.total_amount_payable | intcomma }}</td>
            <td>{{ invoice.total_amount_paid | intcomma }}</td>
            <td>{{ invoice.balance | intcomma }}</td>
            <td><a class="btn btn-success btn-sm"
                href="{% url 'finance:receipt-create' %}?invoice={{ invoice.id }}">Add New
                Payment</a></td>
          </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
  </div>
{% endblock content %}


{% block morejs %}
<script>
   $('#invoicetable').DataTable({
    select: false
    });
</script>

{% endblock morejs %}

finance/templates/finance/receipt_form.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<div class="container-right">
<div class="row">
  <div class="col-8">
    <form action="" method="POST">
      {% csrf_token %}

      {% include 'corecode/form_snippet.html' %}

      <input type="submit" class="btn btn-primary" value="Add payment">

    </form>
  </div>

  <div class="col-4">
    <div class="alert alert-info" role="alert">
      <h3>INVOICE</h3>
      <p>{{invoice | upper}}</p>
      <hr>
      <ul>

        <li>Year: {{ invoice.session }}</li>
        <li>Month: {{ invoice.term }}</li>
        
        <li>Total Amount Payable: {{invoice.total_amount_payable | intcomma }}
        </li>
        <li>Total Amount Paid: {{ invoice.total_amount_paid | intcomma }}</li>
        <li><strong>Balance: {{invoice.balance | intcomma }}</strong></li>
      </ul>
    </div>
  </div>
</div>
</div>
{% endblock content %}